### ISSUE TITLE
Problems with Firebase

### ISSUE THREAD

**Issue by Smurfffy** [Smurfffy/FinalYearProject_MEANIonic2#1]
Firebase doesn't seem to be working out for us like we hoped so we should quickly research some other technologies and have a fully functioning app with these new technologies by the end of the week. We can start implementing new features from there.

**Comment by JasonMcTigue** [comment]
Iv tried a new application using ionic and node which works on a local server. Iv tried to host it on Heroku but it didn't work so I'm trying to host it on firebase at the moment. Iv pushed it to my branch so ye can have a look at it there and see what ye think.

Has anyone else made any progress with their research?
