### ISSUE TITLE
Some Formating with the login page

### ISSUE THREAD

**Issue by Smurfffy** [Smurfffy/FinalYearProject_MEANIonic2#2]
I was trying to make some space between the green login button and the text input boxes on the login page. Margin-Top seems to work with ionic but the value of it I think is locked at 10px and I was trying to change it to something a little bigger I thought I could do this in the login.scss page but I couldn't find a way to. If ye figure anything out let me know but this isn't a big problem at all so don't waste time with it if you can't afford to.

**Comment by JasonMcTigue** [comment]
Cool I will have a look at it and see what I can do

**Comment by JasonMcTigue** [comment]
The layout looks good so I wouldn't worry too much about that. So all we really need to do is add a logout function.
