### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by JasonMcTigue** [Smurfffy/FinalYearProject_MEANIonic2#3]
We need to create a skeleton for our app now because we need to start putting it together properly.

**Comment by Smurfffy** [comment]
Just put together a much better skeleton for our app with a better structure for us to work on what we need. Should also make it easier for us to work on individual features. It's in the skeleton branch at the moment and I'll push it to the master tomorrow after I show you it and you're happy with it.

**Comment by JasonMcTigue** [comment]
Cool that sounds good.
