### ISSUE TITLE
Migrating Firebase with ionic 2

### ISSUE THREAD

**Issue by JasonMcTigue** [Smurfffy/FinalYearProject_MEANIonic2#4]
We need to figure out how to migrate firebase and ionic 2 together. Iv been looking at a few different ways to do it but haven't figured out the correct way so if any of ye have any other solutions let me know.

**Comment by Smurfffy** [comment]
I have firebase migrated into the skeleton we have for ionic to its installed and ready to go

**Comment by JasonMcTigue** [comment]
Perfect ill download that now and add in what I have.
