### ISSUE TITLE
Log out screen

### ISSUE THREAD

**Issue by JasonMcTigue** [Smurfffy/FinalYearProject_MEANIonic2#9]
I'm having an issue with the logout screen. When I log out of the application its logs my account out but then displays the tabs from the application at the bottom of the screen. From this, I can then navigate back into the application when not logged in.
Anyone have any ideas on how to fix this?

**Comment by Smurfffy** [comment]
Found a fix [here](https://forum.ionicframework.com/t/tabs-persist-after-logging-out-of-app-start-stacking-on-log-in/46321/5)

We need the following code in our map.ts file

```
import {App} from 'ionic-angular';
this.app.getRootNav().setRoot(loginScreen);
```

instead of this.
`this.nav.setRoot(loginScreen);`

**Comment by JasonMcTigue** [comment]
That worked perfectly.
